--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Flugins/DiscordHelper
build-by-default: true
branches:
- main
projects:
  DiscordHelper:
    path: ""
    model: virion
    type: library
...
